/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.3
 * Generated at: 2025-03-23 17:28:26 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.project;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.1.jar", Long.valueOf(1739629722434L));
    _jspx_dependants.put("jar:file:/C:/Users/pc/.m2/repository/org/glassfish/web/jakarta.servlet.jsp.jstl/3.0.1/jakarta.servlet.jsp.jstl-3.0.1.jar!/META-INF/c-1_2.tld", Long.valueOf(1664449878000L));
    _jspx_dependants.put("/WEB-INF/components/navbar.jsp", Long.valueOf(1742748611045L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>ConstructionXpert</title>\r\n");
      out.write("    <script\r\n");
      out.write("            src=\"https://kit.fontawesome.com/13885aca87.js\"\r\n");
      out.write("            crossorigin=\"anonymous\"\r\n");
      out.write("    ></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <main class=\"bg-[#eff1f3] min-h-screen w-full pb-6\">\r\n");
      out.write("        <div class=\"container mx-auto flex flex-col px-4\">\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("<nav class=\"w-full py-4\">\r\n");
      out.write("    <div class=\"flex w-full items-center justify-between flex-wrap gap-4\">\r\n");
      out.write("        <div\r\n");
      out.write("                class=\"flex items-center justify-center px-6 py-3 bg-white rounded-[40px]\"\r\n");
      out.write("        >\r\n");
      out.write("            <div\r\n");
      out.write("                    class=\"w-fit [font-family:'Inter',Helvetica] text-xl md:text-2xl text-[#0c0726]\"\r\n");
      out.write("            >\r\n");
      out.write("                <span class=\"font-bold\">Construction</span>\r\n");
      out.write("                <span class=\"font-normal\">Xpert</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"hidden lg:flex items-center gap-2\">\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"w-[60px] h-[60px] flex items-center justify-center bg-white rounded-full hover:bg-gray-50 transition-colors cursor-pointer\"\r\n");
      out.write("            >\r\n");
      out.write("                <a href=\"projects.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-home text-xl text-gray-700\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"w-[60px] h-[60px] flex items-center justify-center bg-white rounded-full hover:bg-gray-50 transition-colors cursor-pointer\"\r\n");
      out.write("            >\r\n");
      out.write("                <a href=\"projects.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-folder text-xl text-gray-700\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"w-[60px] h-[60px] flex items-center justify-center bg-white rounded-full hover:bg-gray-50 transition-colors cursor-pointer\"\r\n");
      out.write("            >\r\n");
      out.write("                <a href=\"projects.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-users text-xl text-gray-700\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"w-[60px] h-[60px] flex items-center justify-center bg-white rounded-full hover:bg-gray-50 transition-colors cursor-pointer\"\r\n");
      out.write("            >\r\n");
      out.write("                <a href=\"projects.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-home text-xl text-gray-700\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"w-[60px] h-[60px] flex items-center justify-center bg-white rounded-full hover:bg-gray-50 transition-colors cursor-pointer\"\r\n");
      out.write("            >\r\n");
      out.write("                <a href=\"projects.jsp\">\r\n");
      out.write("                    <i class=\"fas fa-home text-xl text-gray-700\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"flex items-center gap-3\">\r\n");
      out.write("            <div\r\n");
      out.write("                    class=\"hidden lg:flex items-center gap-3 pl-3 pr-6 py-2 bg-white rounded-[40px]\"\r\n");
      out.write("            >\r\n");
      out.write("                <button\r\n");
      out.write("                        class=\"px-3.5 py-3 rounded-[40px] border border-solid border-[#7b7b7b33] hover:bg-gray-50 transition-colors\"\r\n");
      out.write("                >\r\n");
      out.write("                    <i class=\"fas fa-sign-out-alt text-xl text-gray-700\"></i>\r\n");
      out.write("                </button>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"w-[50px] h-[50px] rounded-full overflow-hidden\">\r\n");
      out.write("                    <img\r\n");
      out.write("                            src=\"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d\"\r\n");
      out.write("                            alt=\"User Profile\"\r\n");
      out.write("                            class=\"w-full h-full object-cover\"\r\n");
      out.write("                    />\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"flex flex-col items-start justify-center gap-1\">\r\n");
      out.write("                    <div class=\"font-semibold text-[#0c0726] text-lg\">\r\n");
      out.write("                        John Doe\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"font-normal text-[#7b7b7b] text-sm m-0\">\r\n");
      out.write("                        adressjohn@gmail.com\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Mobile Menu Button -->\r\n");
      out.write("\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"lg:hidden w-10 h-10 flex items-center justify-center bg-white rounded-full\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-times text-gray-700`\"></i>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Mobile nav menu  -->\r\n");
      out.write("        <div class=\"lg:hidden w-full flex-col bg-white rounded-[20px] p-4\">\r\n");
      out.write("            <div\r\n");
      out.write("                    class=\"flex items-center gap-3 p-4 border-b border-gray-100 mb-2\"\r\n");
      out.write("            >\r\n");
      out.write("                <div class=\"w-[50px] h-[50px] rounded-full overflow-hidden\">\r\n");
      out.write("                    <img\r\n");
      out.write("                            src=\"https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d\"\r\n");
      out.write("                            alt=\"User Profile\"\r\n");
      out.write("                            class=\"w-full h-full object-cover\"\r\n");
      out.write("                    />\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"flex flex-col\">\r\n");
      out.write("                    <div class=\"font-semibold text-[#0c0726] text-lg\">\r\n");
      out.write("                        John Doe\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"font-normal text-[#7b7b7b] text-sm\">\r\n");
      out.write("                        adressjohn@gmail.com\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"flex items-center gap-3 w-full p-3 hover:bg-gray-50 rounded-lg transition-colors\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-home text-gray-700\"></i>\r\n");
      out.write("                <span class=\"text-gray-700\">Home</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"flex items-center gap-3 w-full p-3 hover:bg-gray-50 rounded-lg transition-colors\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-folder text-gray-700\"></i>\r\n");
      out.write("                <span class=\"text-gray-700\">Projects</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"flex items-center gap-3 w-full p-3 hover:bg-gray-50 rounded-lg transition-colors\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-home text-gray-700\"></i>\r\n");
      out.write("                <span class=\"text-gray-700\">Tasks</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"flex items-center gap-3 w-full p-3 hover:bg-gray-50 rounded-lg transition-colors\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-users text-gray-700\"></i>\r\n");
      out.write("                <span class=\"text-gray-700\">Stuff</span>\r\n");
      out.write("            </button>\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"flex items-center gap-3 w-full p-3 hover:bg-gray-50 rounded-lg transition-colors\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-home text-gray-700\"></i>\r\n");
      out.write("                <span class=\"text-gray-700\">Home</span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("            <button\r\n");
      out.write("                    class=\"flex items-center gap-3 w-full p-3 hover:bg-gray-50 rounded-lg transition-colors mt-2 border-t border-gray-100\"\r\n");
      out.write("            >\r\n");
      out.write("                <i class=\"fas fa-sign-out-alt text-gray-700\"></i>\r\n");
      out.write("                <span class=\"text-gray-700\">Logout</span>\r\n");
      out.write("            </button>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"bg-white rounded-[16px] mt-6 overflow-hidden\">\r\n");
      out.write("                    <div class=\"w-full\">\r\n");
      out.write("                        <div\r\n");
      out.write("                                class=\"flex flex-wrap justify-between items-center gap-4 p-6 border-b border-gray-100\"\r\n");
      out.write("                        >\r\n");
      out.write("                            <h2 class=\"text-2xl font-bold text-[#0c0726] basis-full\">\r\n");
      out.write("                                Project&nbsp;&nbsp;&gt;&nbsp;&nbsp;Add Form\r\n");
      out.write("                            </h2>\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                <div\r\n");
      out.write("                                        class=\"gap-8 self-stretch w-full flex flex-col items-start\"\r\n");
      out.write("                                >\r\n");
      out.write("                                    <input\r\n");
      out.write("                                            class=\"h-[50px] w-full px-4 py-2 bg-white rounded-[40px] text-[#7b7b7b] border border-gray-200\"\r\n");
      out.write("                                            placeholder=\"Start date\"\r\n");
      out.write("                                            name=\"startDate\"\r\n");
      out.write("                                            onfocus=\"(this.type='date')\"\r\n");
      out.write("                                            onblur=\"(this.type='text')\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project.startDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                    <input\r\n");
      out.write("                                            class=\"h-[50px] w-full px-4 py-2 bg-white rounded-[40px] text-[#7b7b7b] border border-gray-200\"\r\n");
      out.write("                                            placeholder=\"End date\"\r\n");
      out.write("                                            name=\"endDate\"\r\n");
      out.write("                                            onfocus=\"(this.type='date')\"\r\n");
      out.write("                                            onblur=\"(this.type='text')\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project.endDate}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                    <input\r\n");
      out.write("                                            class=\"h-[50px] w-full px-4 py-2 bg-white rounded-[40px] text-[#7b7b7b] border border-gray-200\"\r\n");
      out.write("                                            placeholder=\"Title\"\r\n");
      out.write("                                            name=\"title\"\r\n");
      out.write("                                            value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project.title}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"\r\n");
      out.write("                                    />\r\n");
      out.write("                                    <textarea\r\n");
      out.write("                                            class=\"h-[150px] w-full px-4 py-2 bg-white rounded-[16px] text-[#7b7b7b] border border-gray-200\"\r\n");
      out.write("                                            placeholder=\"Enter a description\"\r\n");
      out.write("                                            name=\"description\"\r\n");
      out.write("                                    >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project.description}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</textarea>\r\n");
      out.write("                                    <button\r\n");
      out.write("                                            type=\"submit\"\r\n");
      out.write("                                            class=\"h-[50px] w-full bg-[#0c0726] text-white rounded-[40px] font-normal hover:bg-[#1a1642] transition-colors\"\r\n");
      out.write("                                    >\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                                        ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write(" Project\r\n");
      out.write("\r\n");
      out.write("                                    </button>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </form>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/views/admin/project/form.jsp(31,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                <form\r\n");
        out.write("                                        class=\"flex flex-col max-w-[500px] w-[500px] mx-auto my-[32px] items-start justify-center\"\r\n");
        out.write("                                        action=\"edit-project\"\r\n");
        out.write("                                        method=\"post\"\r\n");
        out.write("                                >\r\n");
        out.write("                                    <input hidden=\"hidden\" name=\"id\" value=\"");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project.id}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write("\">\r\n");
        out.write("                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/views/admin/project/form.jsp(39,28) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project == null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                <form\r\n");
        out.write("                                        class=\"flex flex-col max-w-[500px] w-[500px] mx-auto my-[32px] items-start justify-center\"\r\n");
        out.write("                                        action=\"add-project\"\r\n");
        out.write("                                        method=\"post\"\r\n");
        out.write("                                >\r\n");
        out.write("                            ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/views/admin/project/form.jsp(80,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project != null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            Edit\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(jakarta.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    jakarta.servlet.jsp.PageContext pageContext = _jspx_page_context;
    jakarta.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /WEB-INF/views/admin/project/form.jsp(83,40) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope.project == null}", boolean.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != jakarta.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                                            Add\r\n");
        out.write("                                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != jakarta.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == jakarta.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }
}
